# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/io.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axi4stream_spi_master_0_0/design_1_axi4stream_spi_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axi4stream_spi_master_0_0 || ORIG_REF_NAME==design_1_axi4stream_spi_master_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_dual_i2s_0_0/design_1_axis_dual_i2s_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_dual_i2s_0_0 || ORIG_REF_NAME==design_1_axis_dual_i2s_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_0_0/design_1_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_0_0 || ORIG_REF_NAME==design_1_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_1/design_1_clk_wiz_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_1 || ORIG_REF_NAME==design_1_clk_wiz_0_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_volume_controller_0_0/design_1_volume_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_volume_controller_0_0 || ORIG_REF_NAME==design_1_volume_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_balance_controller_0_0/design_1_balance_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_balance_controller_0_0 || ORIG_REF_NAME==design_1_balance_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_LFO_0_0/design_1_LFO_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_LFO_0_0 || ORIG_REF_NAME==design_1_LFO_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_debouncer_0_0/design_1_debouncer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_debouncer_0_0 || ORIG_REF_NAME==design_1_debouncer_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_digilent_jstk2_0_0/design_1_digilent_jstk2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_digilent_jstk2_0_0 || ORIG_REF_NAME==design_1_digilent_jstk2_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_edge_detector_toggle_0_0/design_1_edge_detector_toggle_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_edge_detector_toggle_0_0 || ORIG_REF_NAME==design_1_edge_detector_toggle_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_effect_selector_0_0/design_1_effect_selector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_effect_selector_0_0 || ORIG_REF_NAME==design_1_effect_selector_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_led_controller_0_0/design_1_led_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_led_controller_0_0 || ORIG_REF_NAME==design_1_led_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_led_level_controller_0_0/design_1_led_level_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_led_level_controller_0_0 || ORIG_REF_NAME==design_1_led_level_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_moving_average_filte_0_0/design_1_moving_average_filte_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_moving_average_filte_0_0 || ORIG_REF_NAME==design_1_moving_average_filte_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_mute_controller_0_0/design_1_mute_controller_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_mute_controller_0_0 || ORIG_REF_NAME==design_1_mute_controller_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_edge_detector_toggle_1_0/design_1_edge_detector_toggle_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_edge_detector_toggle_1_0 || ORIG_REF_NAME==design_1_edge_detector_toggle_1_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_axis_broadcaster_0_0/design_1_axis_broadcaster_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_axis_broadcaster_0_0 || ORIG_REF_NAME==design_1_axis_broadcaster_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_proc_sys_reset_1_0/design_1_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_proc_sys_reset_1_0 || ORIG_REF_NAME==design_1_proc_sys_reset_1_0} -quiet] -quiet

# XDC: c:/Users/euzun/Desktop/DESD/LAB3_Eren/lab3_template.xpr/lab3_template/lab3_template.gen/sources_1/bd/design_1/design_1_ooc.xdc
