set_property SRC_FILE_INFO {cfile:{C:/Users/euzun/Desktop/DESD/LAB2_Eren/Piazza files/io.xdc} rfile:{../../../../Piazza files/io.xdc} id:1} [current_design]
set_property SRC_FILE_INFO {cfile:{C:/Users/euzun/Desktop/DESD/LAB2_Eren/Piazza files/basys3_master_xdc.xdc} rfile:{../../../../Piazza files/basys3_master_xdc.xdc} id:2} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J1 [get_ports SPI_M_0_ss_io]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G2 [get_ports SPI_M_0_sck_io]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L2 [get_ports SPI_M_0_io0_io]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J2 [get_ports SPI_M_0_io1_io]
set_property src_info {type:XDC file:2 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports sys_clock]
