# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/euzun/Desktop/DESD/LAB2_Eren/LAB2_Clean_Eren_v2/LAB2_Clean_Eren_v2.srcs/sources_1/bd/Project_1/ip/Project_1_clk_wiz_0/Project_1_clk_wiz_0.xci
# IP: The module: 'Project_1_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/euzun/Desktop/DESD/LAB2_Eren/LAB2_Clean_Eren_v2/LAB2_Clean_Eren_v2.gen/sources_1/bd/Project_1/ip/Project_1_clk_wiz_0/Project_1_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Project_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/euzun/Desktop/DESD/LAB2_Eren/LAB2_Clean_Eren_v2/LAB2_Clean_Eren_v2.gen/sources_1/bd/Project_1/ip/Project_1_clk_wiz_0/Project_1_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Project_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/euzun/Desktop/DESD/LAB2_Eren/LAB2_Clean_Eren_v2/LAB2_Clean_Eren_v2.gen/sources_1/bd/Project_1/ip/Project_1_clk_wiz_0/Project_1_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Project_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/euzun/Desktop/DESD/LAB2_Eren/LAB2_Clean_Eren_v2/LAB2_Clean_Eren_v2.srcs/sources_1/bd/Project_1/ip/Project_1_clk_wiz_0/Project_1_clk_wiz_0.xci
# IP: The module: 'Project_1_clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/euzun/Desktop/DESD/LAB2_Eren/LAB2_Clean_Eren_v2/LAB2_Clean_Eren_v2.gen/sources_1/bd/Project_1/ip/Project_1_clk_wiz_0/Project_1_clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'Project_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/euzun/Desktop/DESD/LAB2_Eren/LAB2_Clean_Eren_v2/LAB2_Clean_Eren_v2.gen/sources_1/bd/Project_1/ip/Project_1_clk_wiz_0/Project_1_clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'Project_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/euzun/Desktop/DESD/LAB2_Eren/LAB2_Clean_Eren_v2/LAB2_Clean_Eren_v2.gen/sources_1/bd/Project_1/ip/Project_1_clk_wiz_0/Project_1_clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Project_1_clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
